name: Update README with recent activity

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@v0.1.4
        with:
          REPO: noelmakubi/noelmakubi
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
